# docker build -f Dockerfile_minimal_publisher -t minimal_publisher .
# docker run --rm --name minimal_publisher-running minimal_publisher

FROM osrf/ros:humble-desktop

ARG USERNAME=rosusr
ARG USER_HOME='/home/rosusr'
ARG PKG_NAME='minimal_publisher'
ARG ROS_WS='/home/rosusr/ros2_ws'

ENV USER_HOME=${USER_HOME}
ENV USERNAME=${USERNAME}
ENV ROS_WS=${ROS_WS}

RUN apt-get update && apt-get install -y \
build-essential \
curl \
htop \
libssl-dev \
locales \
lsb-release \
python3-colcon-common-extensions \
software-properties-common \
wget \
vim \
xterm 

# create workspace
RUN useradd -ms /bin/bash $USERNAME
RUN mkdir -p $ROS_WS/src

# build package
COPY "./${PKG_NAME}" "${ROS_WS}/src/${PKG_NAME}"
RUN chmod -R 765 $ROS_WS
RUN chown -R $USERNAME $USER_HOME
RUN chgrp -R $USERNAME $USER_HOME
USER $USERNAME
RUN cd $ROS_WS && colcon build

# use rosusr user
WORKDIR $ROS_WS